spring:
  application:
    name: application-agent
  ai:
    ollama:
      init:
        pull-model-strategy: when_missing
      embedding:
        enabled: false
      chat:
        enabled: true
        url: http://127.0.0.1:11434
        options:
          model: llama3.2
          temperature: 0.7
    mcp.client:
      sse.connections:
        geocoder-mcp-server:
          url: http://localhost:8081
        timezone-mcp-server:
          url: http://localhost:8082

logging:
  level:
    es.omarall: DEBUG
    org.springframework.ai: DEBUG

